language: node_js

node_js:
- node # will use latest node

branches:
  only:
  - master

before_script: # commands to run before the build step
- npm install -g --silent firebase-tools
- npm install -g --silent @angular/cli

script: # the build step
- ng build --prod

after_success:
- firebase deploy --token $FIREBASE_TOKEN --non-interactive # firebase deploy after angular-cli build
